version: "3.9"

x-app: &app
  env_file:
    - ./.env
  restart: always

services:
  api:
    build:
      context: .
    <<: *app
    volumes:
      - ./:/usr/src/app/
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      api-database:
        condition: service_healthy

  api-migrations:
    build:
      context: .
    <<: *app
    restart: no
    volumes:
      - ./:/usr/src/app/
    depends_on:
      api-database:
        condition: service_healthy
    command: alembic upgrade head

  api-database:
    image: postgres:14
    <<: *app
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U ${NOTIFICATION_POSTGRES_USER} -d ${NOTIFICATION_POSTGRES_DB}'",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - api_db_data:/var/lib/postgresql/data/
    environment:
      TZ: "Europe/Moscow"
      PGTZ: "Europe/Moscow"
    ports:
      - "5432:5432"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus_data/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  api_db_data:
  prometheus_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./prometheus_data
  grafana_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./grafana_data

