apiVersion: batch/v1
kind: Job
metadata:
  name: migrations-job
spec:
  backoffLimit: 2
  activeDeadlineSeconds: 100
  template:
    spec:
      containers:
      - name: backend-container
        image: rozarioagro/k8s-api:latest
        envFrom:
          - secretRef:
              name: api-prod-env
        imagePullPolicy: IfNotPresent
        args:
        - /bin/sh
        - -c
        - alembic upgrade head
      restartPolicy: OnFailure